### ISSUE TITLE
gradle 8.x kts tomls 依赖失败

### ISSUE THREAD

**Issue by GuoFeilong** [ltlovezh/ApkChannelPackage#172]
无法依赖
<img width="1589" alt="image" src="https://github.com/Tencent/VasDolly/assets/12525861/57b568c2-8422-44b8-b917-7932b80a4a89">

**Comment by ChenSiWu** [comment]
1.第一步 在`libs.versions.toml`文件中定义,示例代码如下
```toml
[versions]
# *======== 插件版本 ========
agp = "8.6.1"
kotlin = "2.0.0"
googleDevtoolsKsp = "2.0.0-1.0.24"
#腾讯渠道包 https://github.com/Tencent/VasDolly
tencentVasDolly = "3.0.6"

[libraries]
#腾讯渠道包 https://github.com/Tencent/VasDolly
tencent-vasdolly-helper = { module = "com.tencent.vasdolly:helper", version.ref = "tencentVasDolly" }
tencent-vasdolly-plugin = { module = "com.tencent.vasdolly:plugin", version.ref = "tencentVasDolly" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
tencent-vasdolly = { id = "com.tencent.vasdolly", version.ref = "tencentVasDolly" }
```


第二步在工程的`build.gradle.kts`,示例代码如下
> [!TIP]
> 注意: 需要把`buildscript{}` 放在`plugins {}`的上方
```groovy
buildscript {
    dependencies {
        //腾讯渠道打包https://github.com/Tencent/VasDolly
        classpath(libs.tencent.vasdolly.plugin)
    }
}


// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
}

```
第三部在app目录下的`build.gradle.kts` 示例代码如下
```kotlin
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    ···
    id(libs.plugins.tencent.vasdolly.get().pluginId)
}


android {
    namespace = ···
    compileSdk = ···

    defaultConfig {
        applicationId = ···
        minSdk = ···
        targetSdk = ···
        versionCode = ···
        versionName = ···

        ndk {
            // 设置支持的SO库架构
            //abiFilters 'armeabi', 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
            abiFilters.addAll(setOf("armeabi-v7a", "arm64-v8a"))
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

}

dependencies {
    ···
    implementation(libs.tencent.vasdolly.helper)

}
```
最后就可以导入成功了
![企业微信截图_0dd814ab-b8a9-4f47-b16a-0f9fe47c0db8](https://github.com/user-attachments/assets/cce0652b-346d-4cd7-be04-203c7d723343)

或者参考 #171 的写法也可以同样达到效果
